export const MOCK_SERVICES = [
  {
    id: 'srv-telegram',
    name: 'Telegram',
    code: 'tg',
    icon: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop&q=80',
    color: 'from-sky-500 to-blue-600',
    lowestPrice: 0.45,
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    successRate: '98.5%',
    availableStock: 2450,
  },
  {
    id: 'srv-whatsapp',
    name: 'WhatsApp',
    code: 'wa',
    icon: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=120&auto=format&fit=crop&q=80',
    color: 'from-emerald-500 to-green-600',
    lowestPrice: 0.65,
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    successRate: '99.1%',
    availableStock: 1820,
  },
  {
    id: 'srv-openai',
    name: 'OpenAI / ChatGPT',
    code: 'oa',
    icon: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=120&auto=format&fit=crop&q=80',
    color: 'from-teal-500 to-emerald-600',
    lowestPrice: 0.35,
    country: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    successRate: '97.8%',
    availableStock: 3100,
  },
  {
    id: 'srv-google',
    name: 'Google / YouTube',
    code: 'go',
    icon: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=120&auto=format&fit=crop&q=80',
    color: 'from-red-500 to-amber-500',
    lowestPrice: 0.50,
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    successRate: '96.9%',
    availableStock: 940,
  },
  {
    id: 'srv-discord',
    name: 'Discord',
    code: 'dc',
    icon: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=120&auto=format&fit=crop&q=80',
    color: 'from-indigo-500 to-purple-600',
    lowestPrice: 0.40,
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    successRate: '98.2%',
    availableStock: 1420,
  },
  {
    id: 'srv-twitter',
    name: 'X (Twitter)',
    code: 'tw',
    icon: 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=120&auto=format&fit=crop&q=80',
    color: 'from-slate-700 to-slate-900',
    lowestPrice: 0.55,
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    successRate: '95.4%',
    availableStock: 870,
  },
  {
    id: 'srv-tiktok',
    name: 'TikTok',
    code: 'tt',
    icon: 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=120&auto=format&fit=crop&q=80',
    color: 'from-pink-500 to-rose-600',
    lowestPrice: 0.38,
    country: 'Poland',
    countryCode: 'PL',
    flag: '🇵🇱',
    successRate: '97.1%',
    availableStock: 1650,
  },
  {
    id: 'srv-instagram',
    name: 'Instagram / Meta',
    code: 'ig',
    icon: 'https://images.unsplash.com/photo-1611262588024-d12430b98920?w=120&auto=format&fit=crop&q=80',
    color: 'from-fuchsia-500 to-rose-500',
    lowestPrice: 0.42,
    country: 'Sweden',
    countryCode: 'SE',
    flag: '🇸🇪',
    successRate: '98.0%',
    availableStock: 2100,
  },
  {
    id: 'srv-steam',
    name: 'Steam',
    code: 'st',
    icon: 'https://images.unsplash.com/photo-1612287233207-6b3a27c7f3b8?w=120&auto=format&fit=crop&q=80',
    color: 'from-blue-600 to-slate-800',
    lowestPrice: 0.60,
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    successRate: '99.4%',
    availableStock: 1120,
  },
];

export const MOCK_COUNTRIES = [
  { name: 'All Countries', code: 'ALL', flag: '🌐' },
  { name: 'United States', code: 'US', flag: '🇺🇸' },
  { name: 'United Kingdom', code: 'GB', flag: '🇬🇧' },
  { name: 'Netherlands', code: 'NL', flag: '🇳🇱' },
  { name: 'Germany', code: 'DE', flag: '🇩🇪' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦' },
  { name: 'France', code: 'FR', flag: '🇫🇷' },
  { name: 'Poland', code: 'PL', flag: '🇵🇱' },
  { name: 'Sweden', code: 'SE', flag: '🇸🇪' },
];

export const NUMBER_TYPES = [
  {
    id: 'one-time-otp',
    title: 'One Time OTP',
    badge: 'Standard',
    badgeColor: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
    description: 'Direct SMS verification code with 20 minutes expiration window.',
    priceMultiplier: 1.0,
    features: ['Instant code reception', 'Single verification code', '20 min auto-cancel refund', 'Standard carrier route'],
    recommended: false,
  },
  {
    id: 'multiple-otp',
    title: 'Multiple OTP',
    badge: 'Popular',
    badgeColor: 'bg-sky-500/20 text-sky-400 border-sky-500/30',
    description: 'Receive multiple verification codes on the same number for up to 60 mins.',
    priceMultiplier: 1.6,
    features: ['Unlimited SMS in session', 'Up to 60 minutes window', 'Auto-resend support', 'Tier-1 cellular routes'],
    recommended: true,
  },
  {
    id: 'premium-one-time-otp',
    title: 'Premium One Time OTP',
    badge: 'Clean Line',
    badgeColor: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
    description: '100% clean physical SIM line strictly never recycled on target service.',
    priceMultiplier: 1.8,
    features: ['Physical non-VoIP SIM', 'Guaranteed zero prior reuse', 'Bypass anti-fraud flags', '99.8% delivery speed'],
    recommended: false,
  },
  {
    id: 'premium-multiple-otp',
    title: 'Premium Multiple OTP',
    badge: 'VIP Dedicated',
    badgeColor: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
    description: 'Dedicated private physical SIM channel with full multi-code reception.',
    priceMultiplier: 2.4,
    features: ['Multi-code physical SIM', '2-hour extended session', 'High-priority routing', 'Free number swap'],
    recommended: false,
  },
];

export const RENTAL_CARDS = [
  {
    id: 'rent-one-time',
    title: 'One Time OTP Rent',
    duration: '4 Hours',
    price: 1.80,
    badge: 'Short Term',
    badgeColor: 'bg-emerald-500/15 border-emerald-500/30 text-emerald-400',
    features: ['Single service verification', 'Active for 4 full hours', 'Instant activation', 'Full SMS inbox logs'],
    carrier: 'Physical Tier-1',
  },
  {
    id: 'rent-multiple',
    title: 'Multiple OTP Rent',
    duration: '24 Hours',
    price: 3.50,
    badge: 'Best Value',
    badgeColor: 'bg-sky-500/15 border-sky-500/30 text-sky-400',
    features: ['All services supported', 'Full 24h retention', 'Multiple codes allowed', 'Extendable anytime'],
    carrier: 'Direct Mobile Route',
    popular: true,
  },
  {
    id: 'rent-premium-one-time',
    title: 'Premium One Time Rent',
    duration: '7 Days',
    price: 9.90,
    badge: 'Weekly VIP',
    badgeColor: 'bg-purple-500/15 border-purple-500/30 text-purple-400',
    features: ['Private physical number', 'Never shared or recycled', 'Banking & crypto verified', 'Priority delivery node'],
    carrier: 'Clean Carrier SIM',
  },
  {
    id: 'rent-premium-multiple',
    title: 'Premium Multiple Rent',
    duration: '30 Days',
    price: 28.00,
    badge: 'Monthly Dedicated',
    badgeColor: 'bg-amber-500/15 border-amber-500/30 text-amber-400',
    features: ['30-day dedicated lease', 'Receive SMS from any app', 'Auto-renewal option', 'Dedicated SIM port'],
    carrier: 'Enterprise Dedicated',
  },
];

export const INITIAL_ORDERS = [
  {
    id: 'ORD-8921',
    service: 'Telegram',
    serviceCode: 'tg',
    country: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    phone: '+1 (202) 555-0149',
    numberType: 'One Time OTP',
    code: '849-201',
    price: 0.45,
    status: 'active', // active | completed | cancelled
    expiresInSeconds: 840,
    timestamp: '2 mins ago',
  },
  {
    id: 'ORD-8919',
    service: 'OpenAI / ChatGPT',
    serviceCode: 'oa',
    country: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    phone: '+31 6 1234 5678',
    numberType: 'Premium One Time OTP',
    code: '592-814',
    price: 0.63,
    status: 'active',
    expiresInSeconds: 1120,
    timestamp: '5 mins ago',
  },
  {
    id: 'ORD-8874',
    service: 'WhatsApp',
    serviceCode: 'wa',
    country: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    phone: '+44 7911 123456',
    numberType: 'Multiple OTP',
    code: '338-902',
    price: 1.04,
    status: 'completed',
    expiresInSeconds: 0,
    timestamp: 'Yesterday at 18:42',
  },
  {
    id: 'ORD-8861',
    service: 'Google / YouTube',
    serviceCode: 'go',
    country: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    phone: '+49 151 23456789',
    numberType: 'One Time OTP',
    code: '419-760',
    price: 0.50,
    status: 'completed',
    expiresInSeconds: 0,
    timestamp: '23 Sep 2026',
  },
  {
    id: 'ORD-8810',
    service: 'X (Twitter)',
    serviceCode: 'tw',
    country: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    phone: '+33 6 12 34 56 78',
    numberType: 'Premium One Time OTP',
    code: '—',
    price: 0.99,
    status: 'cancelled',
    expiresInSeconds: 0,
    timestamp: '22 Sep 2026',
  },
];
